In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
training_set= tf.keras.utils.image_dataset_from_directory(
    'animal',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 478 files belonging to 8 classes.


In [6]:
validation_set= tf.keras.utils.image_dataset_from_directory(
    'animal',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 478 files belonging to 8 classes.


In [7]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 8), dtype=tf.float32, name=None))>

In [8]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[1.71957031e+02 1.63623077e+02 1.53721695e+02]
   [1.47798264e+02 1.42345139e+02 1.25661545e+02]
   [7.36829834e+01 7.52611084e+01 5.22554016e+01]
   ...
   [5.12650452e+01 1.05233795e+02 6.48089142e+01]
   [8.38714600e+01 1.37662384e+02 8.90519867e+01]
   [1.04647949e+02 1.60602997e+02 1.12255341e+02]]

  [[1.76763397e+02 1.72069946e+02 1.58933228e+02]
   [1.63308014e+02 1.60581451e+02 1.43208679e+02]
   [9.58996429e+01 9.84777679e+01 7.78566742e+01]
   ...
   [2.61532135e+01 7.34696198e+01 4.98343964e+01]
   [3.84210358e+01 8.64826965e+01 5.90672455e+01]
   [7.18666077e+01 1.20855911e+02 9.40220184e+01]]

  [[1.67923080e+02 1.65752106e+02 1.53632217e+02]
   [1.64203461e+02 1.62493729e+02 1.47146072e+02]
   [1.17543304e+02 1.20310120e+02 1.03204651e+02]
   ...
   [1.10880585e+01 5.48882446e+01 2.37310638e+01]
   [2.40712280e+01 6.47545319e+01 3.91427460e+01]
   [2.08636017e+01 6.40745392e+01 3.77073517e+01]]

  ...

  [[3.33290253e+01 2.32178497e+01 1.78846130e+01]
   [4

In [41]:
from tensorflow.keras.layers import Conv2D,Dense,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [51]:
model=Sequential()

In [52]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [53]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [54]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [55]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [56]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [57]:
model.add(Dropout(0.25))

In [58]:
model.add(Flatten())

In [60]:
model.add(Dense(units=1500,activation='relu'))

In [61]:
model.add(Dropout(0.4))

In [62]:
model.add(Dense(units=8,activation='softmax'))

In [63]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [64]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_31 (Conv2D)                   │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_32 (Conv2D)                   │ (None, 126, 126, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_12 (MaxPooling2D)      │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_33 (Conv2D)                   │ (None, 63, 63, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_34 (Conv2D)                   │ (None, 61, 61, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_13 (MaxPooling2D)      │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_35 (Conv2D)                   │ (None, 30, 30, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_36 (Conv2D)                   │ (None, 28, 28, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_14 (MaxPooling2D)      │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_37 (Conv2D)                   │ (None, 14, 14, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_38 (Conv2D)                   │ (None, 12, 12, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_15 (MaxPooling2D)      │ (None, 6, 6, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_39 (Conv2D)                   │ (None, 6, 6, 512)           │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_40 (Conv2D)                   │ (None, 4, 4, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_16 (MaxPooling2D)      │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 2048)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1500)                │       3,073,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 1500)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 8)                   │          12,008 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 7,797,732 (29.75 MB)

 Trainable params: 7,797,732 (29.75 MB)

 Non-trainable params: 0 (0.00 B)

Model Training

In [65]:
training_history=model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 76s 5s/step - accuracy: 0.1501 - loss: 2.9264 - val_accuracy: 0.1611 - val_loss: 2.0576
Epoch 2/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 75s 5s/step - accuracy: 0.1806 - loss: 2.0629 - val_accuracy: 0.3201 - val_loss: 1.9460
Epoch 3/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 78s 5s/step - accuracy: 0.2592 - loss: 1.9663 - val_accuracy: 0.4059 - val_loss: 1.8164
Epoch 4/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 104s 7s/step - accuracy: 0.3544 - loss: 1.8242 - val_accuracy: 0.4205 - val_loss: 1.6502
Epoch 5/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 122s 6s/step - accuracy: 0.4324 - loss: 1.6386 - val_accuracy: 0.4247 - val_loss: 1.5587
Epoch 6/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 128s 5s/step - accuracy: 0.4255 - loss: 1.5651 - val_accuracy: 0.5188 - val_loss: 1.3484
Epoch 7/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 68s 5s/step - accuracy: 0.4839 - loss: 1.4416 - val_accuracy: 0.5335 - val_loss: 1.2921
Epoch 8/10
15/15 ━━━━━━━━━━━━━━━━━━━━ 83s 5s/step - accuracy: 0.4969 - loss: 1.3701 - val_accuracy: 0.5272 - val_lo

In [66]:
model.save('trained_model.keras')

In [68]:
training_history.history

{'accuracy': [0.1485355645418167,
  0.1736401617527008,
  0.2552301287651062,
  0.3472803235054016,
  0.4142259359359741,
  0.437238484621048,
  0.4895397424697876,
  0.4790794849395752,
  0.5857740640640259,
  0.5836820006370544],
 'loss': [2.4856514930725098,
  2.0480639934539795,
  1.9372981786727905,
  1.8190205097198486,
  1.6418375968933105,
  1.5432078838348389,
  1.435928463935852,
  1.4104764461517334,
  1.232526183128357,
  1.145682692527771],
 'val_accuracy': [0.16108787059783936,
  0.3200836777687073,
  0.40585774183273315,
  0.42050209641456604,
  0.4246861934661865,
  0.5188284516334534,
  0.5334727764129639,
  0.5271966457366943,
  0.625523030757904,
  0.7050209045410156],
 'val_loss': [2.057619333267212,
  1.9459667205810547,
  1.8163912296295166,
  1.6501880884170532,
  1.5587475299835205,
  1.3484368324279785,
  1.2920588254928589,
  1.2794057130813599,
  1.0136535167694092,
  0.892571747303009]}

In [69]:
#Recording the history in json
import json
with open ("training_hist.json","w") as f :
    json.dump(training_history.history,f)